// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperVendas.DbContextFiles;

#nullable disable

namespace SuperVendas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209203439_primeiro-migration")]
    partial class primeiromigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");
#pragma warning restore 612, 618
        }
    }
}
